### ISSUE TITLE
能关闭第三方脚本检测吗

### ISSUE THREAD

**Issue by 2284787774** [demoshang/autojs-scripts#15]
手机是多开京东，每次第三方脚本检测就重新打开主京东

**Comment by demoshang** [comment]
"第三方脚本检测"  是下载别人的  淘宝双十一 脚本

多开京东 没有做兼容, 我手机只支持 淘宝多开, 不支持 京东多开

"每次第三方脚本检测就重新打开主京东"  应该是触发重试机制了, 如果遇到无法处理的情况, 就会关闭 京东, 然后重新打开, 可能会触发到 第三方脚本
